"""
Django settings for pharmaceuticaBackend project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2m8p0w0#us+rqt(9mt@+&9io7v_ltvn^kobp3+8mku#5fcu9dk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

if os.getcwd() == '/app':
    DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_redis',
     'django_daraja',
     'rest_framework_simplejwt',


    'accounts', 
    'product',
    'category',
    'order',
    'cart',
    'shipping',
    'payment',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',


    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
]

ROOT_URLCONF = 'pharmaceuticaBackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pharmaceuticaBackend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }



DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'medswift',
        'USER': 'postgres',
        'PASSWORD': 'RonG254k',
        'HOST': 'localhost',
        'PORT': '5432',
    }

}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'


STATIC_URL = 'banner/static/'
MEDIA_URL = '/products/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


CORS_ORIGIN_ALLOW_ALL = True
ACESS_CONTROL_ALLOW_ORIGIN = True

CORS_ALLOWED_ORIGINS = [

    "http://localhost:8000",
    "http://localhost:3000",
    "http://192.168.1.103"

]



CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://localhost:6379/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
    }
}


SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'



REST_FRAMEWORK = {
 
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        # 'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    )
  
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'





MPESA_ENVIRONMENT = 'sandbox'

# Credentials for the daraja app

MPESA_CONSUMER_KEY = '65hJEgJ7TYuZZwPGdGndnGagpU3Nn6AdAJFr62ddYMB0RE4h'
MPESA_CONSUMER_SECRET = 'GUaqqMGOLRNAMemU3nOVesbsJn5vGdSGkSWuqaKoX2IhnhyT3bACCRhwYgpU66HV'

#Shortcode to use for transactions. For sandbox  use the Shortcode 1 provided on test credentials page

MPESA_SHORTCODE = '174379'

MPESA_BASE_URL = 'https://sandbox.safaricom.co.ke'

MPESA_EXPRESS_SHORTCODE = '174379'


MPESA_SHORTCODE_TYPE = 'paybill'



MPESA_PASSKEY = 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919'


MPESA_INITIATOR_USERNAME = 'Safaricom999!*!'


MPESA_INITIATOR_SECURITY_CREDENTIAL = 'Q13Yw0HHEOEqZV2J0J7hhQtqY7uflpydMYOBdgRibSmY3DJDZnjWbuuPPrH265PNlCWeNf/6dslMS7P3exLZRnpcb5cxtzOaVfxWaTK1gJCP85N90BHnb70PxlA+yNAqqgcHRC43/zGNuGR4tt0ZjJyLqZXAnYRFMgmswu1f9Wf6dutcMcAlsNsbVysVjonIm1QdAzvoLGOcUCtm8esJ+ByioqILUjbuTbiqPJ3h5+KOeAnfccaPud9KYmm4A7cCivre+ZswDmZG2ovZmB7SnbExoeYfo3ySFH2lZhG4AQSQeNvL2EUWU0hVbB1x1wahkXNnUX9I17j1fk/oLwpCnQ=='