# Generated by Django 5.0.6 on 2024-05-08 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2024, 5, 8, 10, 31, 37, 898284, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='date_updated',
            field=models.DateField(default=datetime.datetime(2024, 5, 8, 10, 31, 45, 413089, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='time_created',
            field=models.TimeField(default=datetime.datetime(2024, 5, 8, 10, 31, 52, 59199, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
