# Generated by Django 5.0.6 on 2024-06-03 09:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MpesaTransaction',
            new_name='MpesaPaymentTransaction',
        ),
    ]
