# Generated by Django 5.0.6 on 2024-08-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_mpesatransaction_mpesapaymenttransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesapaymenttransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
