# Generated by Django 5.0.6 on 2024-05-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cartitem_product_cartitem_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
