# Generated by Django 5.0.6 on 2024-05-20 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_cartitem_user_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='time_created',
            field=models.TimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 20, 4, 48, 16, 534652, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
