# Generated by Django 5.0.6 on 2024-08-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='creationTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
