# Generated by Django 5.0.6 on 2024-05-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename__id_order_id_remove_order_shippingprice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='taxPrice',
        ),
        migrations.AlterField(
            model_name='order',
            name='paidAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
