# Generated by Django 5.0.6 on 2024-05-21 02:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_taxprice_alter_order_paidat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='isPaid',
            new_name='is_paid',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='paymentMethod',
            new_name='payment_method',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='totalPrice',
            new_name='total_price',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='createdAt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
